#include <Weather2\clear-day.h> 
#include <Weather2\clear-night.h> 
#include <Weather2\cloudy.h> 
#include <Weather2\drizzle.h> 
#include <Weather2\fog.h> 
#include <Weather2\hail.h> 
#include <Weather2\lightRain.h> 
#include <Weather2\partly-cloudy-day.h> 
#include <Weather2\partly-cloudy-night.h> 
#include <Weather2\rain.h> 
#include <Weather2\sleet.h> 
#include <Weather2\snow.h> 
#include <Weather2\thunderstorm.h> 
#include <Weather2\unknown.h> 
#include <Weather2\wind.h> 
